---
- name: ensure package
  block:
    - import_tasks: environment.yml
    - import_tasks: apt.yml
      when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'
    - import_tasks: yum-packages.yml
      when: ansible_distribution == 'CentOS'
  tags:
    - package
