---
- name: ensure apt configuration is in place
  template:
    src: "apt.conf.d.99apt.j2"
    dest: "/etc/apt/apt.conf.d/99apt"
  become: true

- name: ensure apt packages are installed
  apt:
    pkg: "{{ item }}"
    install_recommends: false
    state: "present"
    update_cache: true
    cache_valid_time: 86400
  loop: "{{ packages }}"
  become: true
