---
- name: ensure package
  block:
    - import_tasks: environment.yml
    - import_tasks: repository-keys.yml
    - import_tasks: repositories.yml
    - import_tasks: cache.yml
    - import_tasks: packages.yml
  tags:
    - package
