---
- import_tasks: packages.yml
  vars:
    package_packages:
      - name: "gpg"
      - name: "gpg-agent"

- name: ensure apt repository keys
  ansible.builtin.apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
    state: "{{ item.state | default(package_apt_key_state) }}"
  loop: "{{ package_repository_keys }}"
  become: true
